# Generated by Django 5.2.8 on 2025-12-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
