# Generated by Django 5.2.8 on 2025-12-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
