# Generated by Django 5.2.8 on 2025-12-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_courseoffering_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoffering',
            old_name='grade',
            new_name='grade_level',
        ),
    ]
