# Generated by Django 5.2.8 on 2025-12-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_grade_courseoffering_grade_level'),
        ('user', '0004_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'grade_level', 'year', 'batch')},
        ),
    ]
