# Generated by Django 5.2.8 on 2025-12-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_enrollmentpayment_payment_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
    ]
