# Generated by Django 5.2.8 on 2025-12-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_grade_courseoffering_grade_level'),
        ('enrollment', '0004_remove_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_offering',
            field=models.ForeignKey(default=1234567, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course.courseoffering'),
            preserve_default=False,
        ),
    ]
